{
	"version": 1741351365,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/redlightgreenlighthowto-sheet0.png",
		"images/redlightgreenlighthowto-sheet1.png",
		"images/redlightgreenlighthowto-sheet2.png",
		"images/play-sheet0.png",
		"images/sky-sheet0.png",
		"images/towers-sheet0.png",
		"images/baredwirewithwall-sheet0.png",
		"images/sand-sheet0.png",
		"images/homer-sheet0.png",
		"images/trump-sheet0.png",
		"images/illegal-sheet0.png",
		"images/illegal-sheet1.png",
		"images/g1-sheet0.png",
		"images/sprite-sheet0.png",
		"images/b1-sheet0.png",
		"images/chopper-sheet0.png",
		"images/topfan-sheet0.png",
		"images/sidefan-sheet0.png",
		"images/sprite2sheet-sheet0.png",
		"images/informationbutton-sheet0.png",
		"images/woman1-sheet0.png",
		"images/woman2-sheet0.png",
		"media/tap.m4a",
		"media/tap.ogg",
		"media/puch 1.m4a",
		"media/puch 1.ogg",
		"media/puch 2.m4a",
		"media/puch 2.ogg",
		"media/puch 3.m4a",
		"media/puch 3.ogg",
		"media/puch 4.m4a",
		"media/puch 4.ogg",
		"media/game over trump.m4a",
		"media/game over trump.ogg",
		"media/trump2.m4a",
		"media/trump2.ogg",
		"media/trump1.m4a",
		"media/trump1.ogg",
		"media/trump3.m4a",
		"media/trump3.ogg",
		"media/wilhelm scream.m4a",
		"media/wilhelm scream.ogg",
		"media/us border bgm.m4a",
		"media/us border bgm.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}